name: CI/CD Pipeline

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  test:
    runs-on: ubuntu-latest      
    
    env:
      BASE_URL: ${{ secrets.API_BASE_URL }}

    
    services:
      postgres:
        image: postgres:16
        env:
          POSTGRES_PASSWORD: postgres
          POSTGRES_USER: postgres
          POSTGRES_DB: dbchat
        options: >-
          --health-cmd pg_isready
          --health-interval 10s
          --health-timeout 5s
          --health-retries 5
        ports:
          - 5432:5432

    steps:
    - name: Checkout code
      uses: actions/checkout@v4

    - name: Setup Node.js
      uses: actions/setup-node@v4
      with:
        node-version: '20'
        cache: 'npm'
        cache-dependency-path: './nestjs/package.json'

    - name: Install dependencies
      run: npm i
      working-directory: ./nestjs

    - name: Generate Prisma Client
      run: npx prisma generate
      working-directory: ./nestjs

    - name: Run database migrations
      run: npx prisma migrate deploy
      working-directory: ./nestjs
      env:
        DATABASE_URL: postgresql://postgres:postgres@localhost:5432/dbchat

    - name: Seed database (optional)
      run: npx prisma db seed
      working-directory: ./nestjs
      env:
        DATABASE_URL: postgresql://postgres:postgres@localhost:5432/dbchat
      continue-on-error: true

    - name: Run unit tests
      run: npm run test
      working-directory: ./nestjs
      env:
        DATABASE_URL: postgresql://postgres:postgres@localhost:5432/dbchat
        NODE_ENV: test
      continue-on-error: true

    - name: Run e2e tests
      run: npm run test:e2e
      working-directory: ./nestjs
      env:
        DATABASE_URL: postgresql://postgres:postgres@localhost:5432/dbchat
        NODE_ENV: test
      continue-on-error: true

    - name: Run test coverage
      run: npm run test:cov
      working-directory: ./nestjs
      env:
        DATABASE_URL: postgresql://postgres:postgres@localhost:5432/dbchat
        NODE_ENV: test
      continue-on-error: true

    - name: Upload coverage reports
      uses: codecov/codecov-action@v3
      with:
        file: ./coverage/lcov.info
        flags: unittests
        name: codecov-umbrella
      continue-on-error: true

    - name: Run Newman tests
      run: newman run ProjetWebQueries.postman_collection.json -e ProjetWebQueries.postman_collection.json
      working-directory: ./nestjs
